# Default values for k8s-mediaserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

general:
  ingress_host: media.edmee.cloud
  plex_ingress_host: plex.media.edmee.cloud
  jellyfin_ingress_host: jellyfin.media.edmee.cloud
  image_tag: latest
  podDistribution: cluster # can be "spread" or "cluster"
  #UID to run the process with
  puid: 1000
  # GID to run the process with
  pgid: 1000
  # Persistent storage selections and pathing
  storage:
    customVolume: false # set to true if not using a PVC (must provide volume below)
    pvcName: mediaserver-pvc
    accessMode: ""
    size: 20Gi
    pvcStorageClass: "rook-cephfs"
    # the path starting from the top level of the pv you're passing. If your share is server.local/share/, then tv is server.local/share/media/tv
    subPaths:
      tv: media/tv
      movies: media/movies
      downloads: downloads
      transmission: transmission
      sabnzbd: sabnzbd
      config: config
    volumes: {}
    #  hostPath:
    #    path: /mnt/share
  ingress:
    ingressClassName: "nginx"
  nodeSelector: {}

sonarr:
  enabled: true
  container:
    image: harbor.infra.edmee.cloud/docker/linuxserver/sonarr
    nodeSelector: {}
    port: 8989
  service:
    type: ClusterIP
    port: 8989
    nodePort:
    extraLBService: false
    extraLBAnnotations: {}
    # Defines an additional LB service, requires cloud provider service or MetalLB
  ingress:
    enabled: true
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-edmee-net
    path: /sonarr
    tls:
      enabled: true
      secretName: "media.edmee.cloud-tls"
  resources: {}
  volume: {}
  # name: pvc-sonarr-config
  # storageClassName: longhorn
  # annotations:
  #   my-annotation/test: my-value
  # labels:
  #   my-label/test: my-other-value
  # accessModes: ReadWriteOnce
  # storage: 5Gi
  # selector: {}

radarr:
  enabled: true
  container:
    image: harbor.infra.edmee.cloud/docker/linuxserver/radarr
    nodeSelector: {}
    port: 7878
  service:
    type: ClusterIP
    port: 7878
    nodePort:
    # Defines an additional LB service, requires cloud provider service or MetalLB
    extraLBService: false
    extraLBAnnotations: {}
  ingress:
    enabled: true
    annotations: {}
    path: /radarr
    tls:
      enabled: true
      secretName: "media.edmee.cloud-tls"
  resources: {}
  volume: {}
  # name: pvc-radarr-config
  # storageClassName: longhorn
  # annotations: {}
  # labels: {}
  # accessModes: ReadWriteOnce
  # storage: 5Gi
  # selector: {}

jackett:
  enabled: true
  container:
    image: harbor.infra.edmee.cloud/docker/linuxserver/jackett
    nodeSelector: {}
    port: 9117
  service:
    type: ClusterIP
    port: 9117
    nodePort:
    extraLBService: false
    extraLBAnnotations: {}
    # Defines an additional LB service, requires cloud provider service or MetalLB
  ingress:
    enabled: true
    annotations: {}
    path: /jackett
    tls:
      enabled: true
      secretName: "media.edmee.cloud-tls"
  resources: {}
  volume: {}
  #  name: pvc-jackett-config
  #  storageClassName: longhorn
  #  annotations: {}
  #  labels: {}
  #  accessModes: ReadWriteOnce
  #  storage: 5Gi
  #  selector: {}

transmission:
  enabled: true
  container:
    image: harbor.infra.edmee.cloud/docker/linuxserver/transmission
    nodeSelector: {}
    port:
      utp: 9091
      peer: 51413
  service:
    utp:
      type: ClusterIP
      port: 9091
      # if type is NodePort, nodePort must be set
      nodePort:
      # Defines an additional LB service, requires cloud provider service or MetalLB
      extraLBService: false
      extraLBAnnotations: {}
    peer:
      type: ClusterIP
      port: 51413
      # if type is NodePort, nodePort and nodePortUDP must be set
      nodePort:
      nodePortUDP:
      # Defines an additional LB service, requires cloud provider service or MetalLB
      extraLBService: false
      extraLBAnnotations: {}
  ingress:
    enabled: true
    annotations: {}
    path: /transmission
    tls:
      enabled: true
      secretName: "media.edmee.cloud-tls"
  config:
    auth:
      enabled: false
      username: ""
      password: ""
  resources: {}
  volume: {}
  #  name: pvc-transmission-config
  #  storageClassName: longhorn
  #  annotations: {}
  #  labels: {}
  #  accessModes: ReadWriteOnce
  #  storage: 5Gi
  #  selector: {}

sabnzbd:
  enabled: true
  container:
    image: harbor.infra.edmee.cloud/docker/linuxserver/sabnzbd
    nodeSelector: {}
    port:
      http: 8080
      https: 9090
  service:
    http:
      type: ClusterIP
      port: 8080
      nodePort:
      # Defines an additional LB service, requires cloud provider service or MetalLB
      extraLBService: false
      extraLBAnnotations: {}
    https:
      type: ClusterIP
      port: 9090
      nodePort:
      # Defines an additional LB service, requires cloud provider service or MetalLB
      extraLBService: false
      extraLBAnnotations: {}
  ingress:
    enabled: true
    annotations: {}
    path: /sabnzbd
    tls:
      enabled: true
      secretName: "media.edmee.cloud-tls"
  resources: {}
  volume: {}
  #  name: pvc-plex-config
  #  storageClassName: longhorn
  #  annotations: {}
  #  labels: {}
  #  accessModes: ReadWriteOnce
  #  storage: 5Gi
  #  selector: {}

prowlarr:
  enabled: true
  container:
    image: harbor.infra.edmee.cloud/docker/linuxserver/prowlarr
    tag: develop
    nodeSelector: {}
    port: 9696
  service:
    type: ClusterIP
    port: 9696
    nodePort:
    extraLBService: false
    extraLBAnnotations: {}
  ingress:
    enabled: true
    annotations: {}
    path: /prowlarr
    tls:
      enabled: true
      secretName: "media.edmee.cloud-tls"
  resources: {}
  volume: {}
  #  name: pvc-prowlarr-config
  #  storageClassName: longhorn
  #  annotations: {}
  #  labels: {}
  #  accessModes: ReadWriteOnce
  #  storage: 5Gi
  #  selector: {}

plex:
  enabled: true
  claim: "CHANGEME"
  replicaCount: 1
  container:
    image: harbor.infra.edmee.cloud/docker/linuxserver/plex
    nodeSelector: {}
    port: 32400
  service:
    type: ClusterIP
    port: 32400
    nodePort:
    # Defines an additional LB service, requires cloud provider service or MetalLB
    extraLBService: false
    extraLBAnnotations: {}
  ingress:
    enabled: true
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-edmee-net
    tls:
      enabled: true
      secretName: "plex.media.edmee.cloud-tls"
  resources: {}
  #  limits:
  #    cpu: 100m
  #    memory: 100Mi
  #  requests:
  #    cpu: 100m
  #    memory: 100Mi
  volume: {}
  #  name: pvc-plex-config
  #  storageClassName: longhorn
  #  annotations: {}
  #  labels: {}
  #  accessModes: ReadWriteOnce
  #  storage: 5Gi
  #  selector: {}

jellyfin:
  enabled: false
  replicaCount: 1
  container:
    image: harbor.infra.edmee.cloud/docker/linuxserver/jellyfin
    nodeSelector: {}
    port: 8096
  service:
    type: ClusterIP
    port: 8096
    nodePort:
    # Defines an additional LB service, requires cloud provider service or MetalLB
    extraLBService: false
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-edmee-net
    tls:
      enabled: true
      secretName: "jellyfin.media.edmee.cloud-tls"
  resources: {}
  #  limits:
  #    cpu: 100m
  #    memory: 100Mi
  #  requests:
  #    cpu: 100m
  #    memory: 100Mi
  volume: {}
  #  name: pvc-jellyfin-config
  #  storageClassName: longhorn
  #  annotations: {}
  #  labels: {}
  #  accessModes: ReadWriteOnce
  #  storage: 5Gi
  #  selector: {}
