{
 "title": "Backtest - Comparaison stratégies",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "backtest_name",
    "label": "backtest_name",
    "query": "SELECT name AS backtestName \nFROM BT_backtests;\n"
   },
   {
    "name": "symbol",
    "label": "symbol",
    "query": "SELECT DISTINCT symbol \nFROM BT_strategies \nWHERE backtestId = (\n    SELECT id FROM BT_backtests WHERE name = '${backtest_name}'\n);\n"
   },
   { "name": "leverage", "label": "Leverage", "query": "1,2,3,4,5" }
  ]
 },
 "panels": [
  {
   "title": "Comparaison stratégies",
   "type": "table",
   "gridPos": { "h": 18, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "backtest",
     "rawSql": "SELECT \r\n    s.id,\r\n    s.timeframe,\r\n    s.coeff0,\r\n    s.coeff1,\r\n    s.coeff2,\r\n    s.coeff3,\r\n    s.coeff4,\r\n    COUNT(t.id) AS trade_count,\r\n    ROUND(STDDEV(\r\n        CASE \r\n            WHEN t.type = 'LONG' THEN ((t.closePrice - t.entryPrice) / t.entryPrice) * ${leverage} * 100 - ((${leverage}*2*0.1) + 0.1)\r\n            WHEN t.type = 'SHORT' THEN ((t.entryPrice - t.closePrice) / t.entryPrice) * ${leverage} * 100 - ((${leverage}*2*0.1) + 0.1)\r\n        END\r\n    ), 2) AS profit_stddev,\r\n    ROUND(AVG(\r\n        CASE \r\n            WHEN t.type = 'LONG' THEN ((t.closePrice - t.entryPrice) / t.entryPrice) * ${leverage} * 100 - ((${leverage}*2*0.1) + 0.1)\r\n            WHEN t.type = 'SHORT' THEN ((t.entryPrice - t.closePrice) / t.entryPrice) * ${leverage} * 100 - ((${leverage}*2*0.1) + 0.1)\r\n        END\r\n    ), 2) AS avg_profit_percentage,\r\n    ROUND(SUM(\r\n        CASE \r\n            WHEN t.type = 'LONG' THEN ((t.closePrice - t.entryPrice) / t.entryPrice) * ${leverage} * 100 - ((${leverage}*2*0.1) + 0.1)\r\n            WHEN t.type = 'SHORT' THEN ((t.entryPrice - t.closePrice) / t.entryPrice) * ${leverage} * 100 - ((${leverage}*2*0.1) + 0.1)\r\n        END\r\n    ), 2) AS total_relative_profit_ajusted,\r\n    ROUND(SUM(\r\n        CASE \r\n            WHEN t.type = 'LONG' THEN ((t.closePrice - t.entryPrice) / t.entryPrice) * 100 \r\n            WHEN t.type = 'SHORT' THEN ((t.entryPrice - t.closePrice) / t.entryPrice) * 100 \r\n        END\r\n    ), 2) AS total_relative_profit\r\nFROM \r\n    BT_strategies s\r\nLEFT JOIN \r\n    BT_trades t ON s.id = t.strategyId\r\nWHERE \r\n    s.backtestId = (SELECT id FROM BT_backtests WHERE name = '${backtest_name}')\r\n    AND s.symbol = '${symbol}'\r\nGROUP BY \r\n    s.id\r\nORDER BY\r\n    total_relative_profit DESC\r\nLIMIT 100;\r\n"
    }
   ]
  },
  {
   "title": "Stratégies évaluées",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "backtest",
     "rawSql": "SELECT \r\n    COUNT(s.id) AS strategy_count\r\nFROM \r\n    BT_strategies s\r\nJOIN \r\n    BT_backtests b ON s.backtestId = b.id\r\nWHERE \r\n    b.name = '${backtest_name}'\r\n    AND s.symbol = '${symbol}';\r\n"
    }
   ]
  },
  {
   "title": "Stratégies Conservées",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "backtest",
     "rawSql": "SELECT \r\n    COUNT(DISTINCT s.id) AS strategy_count\r\nFROM \r\n    BT_strategies s\r\nJOIN \r\n    BT_backtests b ON s.backtestId = b.id\r\nJOIN \r\n    BT_trades t ON s.id = t.strategyId\r\nWHERE \r\n    b.name = '${backtest_name}'\r\n    AND s.symbol = '${symbol}';\r\n"
    }
   ]
  }
 ]
}