{
 "title": "Backtest_V3",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "backtest_name",
    "label": "backtest_name",
    "query": "SELECT name AS backtestName \nFROM BT_backtests;\n"
   },
   {
    "name": "strategy_id",
    "label": "Id de Stratégie",
    "query": "SELECT \n    s.id AS strategy_id\nFROM \n    BT_strategies s\nJOIN \n    BT_backtests b ON s.backtestId = b.id\nWHERE \n    b.name = '${backtest_name}';\n"
   },
   { "name": "leverage", "label": "Leverage", "query": "1,2,3,4,5" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Moyenne de la durée des trades",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "backtest",
     "rawSql": "SELECT \r\n    DISTINCT symbol as symbol,\r\n    timeframe as Timeframe,\r\n    coeff0,\r\n    coeff1,\r\n    coeff2,\r\n    coeff3,\r\n    coeff4,\r\n    creationTs as \"Start Time\"\r\nFROM \r\n    BT_strategies st\r\nWHERE \r\n    st.id = '${strategy_id}';\r\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "dataset": "backtest",
     "rawSql": "SELECT \r\n    t.id AS trade_id,\r\n    t.entryTs AS entryTimestamp,\r\n    t.closeTs AS closeTimestamp,\r\n    t.type AS trade_type,\r\n    TIMESTAMPDIFF(HOUR, t.entryTs, t.closeTs) AS duration_hours,\r\n    t.entryPrice,\r\n    t.closePrice,\r\n    ROUND(\r\n        CASE \r\n            WHEN t.type = 'LONG' THEN ((t.closePrice - t.entryPrice) / t.entryPrice) * ${leverage} * 100 - ((${leverage}*2*0.1) + 0.1)\r\n            WHEN t.type = 'SHORT' THEN ((t.entryPrice - t.closePrice) / t.entryPrice) * ${leverage} * 100 - ((${leverage}*2*0.1) + 0.1)\r\n        END, 2\r\n    ) AS profit_percentage\r\nFROM \r\n    BT_trades t\r\nJOIN \r\n    BT_strategies s ON t.strategyId = s.id\r\nJOIN \r\n    BT_backtests b ON s.backtestId = b.id\r\nWHERE \r\n    b.name = '${backtest_name}'\r\n    AND s.id = '${strategy_id}';\r\n"
    }
   ]
  },
  {
   "title": "Ecrat Type de profits",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "backtest",
     "rawSql": "SELECT \r\n    ROUND(STDDEV(\r\n        CASE \r\n            WHEN t.type = 'LONG' THEN ((t.closePrice - t.entryPrice) / t.entryPrice) * ${leverage} * 100 - ((${leverage}*2*0.1) + 0.1)\r\n            WHEN t.type = 'SHORT' THEN ((t.entryPrice - t.closePrice) / t.entryPrice) * ${leverage} * 100 - ((${leverage}*2*0.1) + 0.1)\r\n        END\r\n    ), 2) AS profit_stddev_percentage\r\nFROM \r\n    BT_trades t\r\nWHERE \r\n    t.strategyId = '${strategy_id}';\r\n"
    }
   ]
  },
  {
   "title": "Pourcentage de trades positifs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "backtest",
     "rawSql": "SELECT \r\n    ROUND((SUM(\r\n        CASE \r\n            WHEN (\r\n                (t.type = 'LONG' AND ((t.closePrice - t.entryPrice)/t.entryPrice * ${leverage} * 100 - ((${leverage}*2*0.1) + 0.1)) > 0) OR\r\n                (t.type = 'SHORT' AND ((t.entryPrice - t.closePrice)/t.entryPrice * ${leverage} * 100 - ((${leverage}*2*0.1) + 0.1)) > 0)\r\n            ) THEN 1 ELSE 0 END\r\n    ) / COUNT(*)) * 100, 2) AS positive_trade_percentage\r\nFROM \r\n    BT_trades t\r\nWHERE \r\n    t.strategyId = '${strategy_id}';\r\n"
    }
   ]
  },
  {
   "title": "Moyenne des profits en pourcentage",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 7, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "backtest",
     "rawSql": "SELECT \r\n    ROUND(AVG(\r\n        CASE \r\n            WHEN t.type = 'LONG' THEN ((t.closePrice - t.entryPrice) / t.entryPrice) * ${leverage} * 100 - ((${leverage}*2*0.1) + 0.1)\r\n            WHEN t.type = 'SHORT' THEN ((t.entryPrice - t.closePrice) / t.entryPrice) * ${leverage} * 100 - ((${leverage}*2*0.1) + 0.1)\r\n        END\r\n    ), 2) AS avg_profit_percentage\r\nFROM \r\n    BT_trades t\r\nWHERE \r\n    t.strategyId = '${strategy_id}';\r\n"
    }
   ]
  },
  {
   "title": "Bénéfices totaux par rapport à une mise de trade",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "backtest",
     "rawSql": "SELECT \r\n    ROUND(SUM(\r\n        CASE \r\n            WHEN t.type = 'LONG' THEN ((t.closePrice - t.entryPrice) / t.entryPrice) * ${leverage} * 100 - ((${leverage}*2*0.1) + 0.1)\r\n            WHEN t.type = 'SHORT' THEN ((t.entryPrice - t.closePrice) / t.entryPrice) * ${leverage} * 100 - ((${leverage}*2*0.1) + 0.1)\r\n        END\r\n    ), 2) AS total_profit_percentage\r\nFROM \r\n    BT_trades t\r\nWHERE \r\n    t.strategyId = '${strategy_id}';\r\n"
    }
   ]
  },
  {
   "title": "Nombre total de trades",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": " Trades" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "backtest",
     "rawSql": "SELECT \r\n    COUNT(t.id) AS trade_count\r\nFROM \r\n    BT_trades t\r\nWHERE \r\n    t.strategyId = '${strategy_id}';\r\n"
    }
   ]
  },
  {
   "title": "Moyenne de la durée des trades",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "backtest",
     "rawSql": "SELECT \r\n    ROUND(AVG(TIMESTAMPDIFF(SECOND, t.entryTs, t.closeTs)), 2) AS avg_trade_duration_seconds\r\nFROM \r\n    BT_trades t\r\nWHERE \r\n    t.strategyId = '${strategy_id}';\r\n"
    }
   ]
  },
  {
   "title": "HIstorical",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "dataset": "backtest",
     "rawSql": "SELECT \r\n    t.closeTs AS closeTimestamp,\r\n    DATE_FORMAT(t.closeTs, '%Y-%m') AS month,\r\n    @cumulative_profit := @cumulative_profit + \r\n    CASE \r\n        WHEN t.type = 'LONG' THEN ((t.closePrice - t.entryPrice) / t.entryPrice) * 100 * ${leverage} - ((${leverage}+1)*0.15 + 0.1)\r\n        WHEN t.type = 'SHORT' THEN ((t.entryPrice - t.closePrice) / t.entryPrice) * 100 * ${leverage} - ((${leverage}+1)*0.15 + 0.1)\r\n    END AS cumulative_portfolio_percentage,\r\n    COUNT(*) OVER (PARTITION BY DATE_FORMAT(t.closeTs, '%Y-%m')) AS trade_count,\r\n    ROUND(SUM(\r\n        CASE \r\n            WHEN t.type = 'LONG' THEN ((t.closePrice - t.entryPrice) / t.entryPrice) * ${leverage} * 100 - ((${leverage}*2*0.1) + 0.1)\r\n            WHEN t.type = 'SHORT' THEN ((t.entryPrice - t.closePrice) / t.entryPrice) * ${leverage} * 100 - ((${leverage}*2*0.1) + 0.1)\r\n        END\r\n    ) OVER (PARTITION BY DATE_FORMAT(t.closeTs, '%Y-%m')), 2) AS monthly_profit_percentage\r\nFROM \r\n    BT_trades t, \r\n    (SELECT @cumulative_profit := 0) AS init\r\nWHERE \r\n    t.strategyId = '${strategy_id}'\r\n    AND t.closeTs IS NOT NULL\r\nORDER BY \r\n    t.closeTs ASC;\r\n"
    }
   ]
  },
  {
   "title": "Répartition du bénéfice des trades",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "." } },
   "targets": [
    {
     "dataset": "backtest",
     "rawSql": "SELECT\r\n  CASE\r\n    WHEN profit_percentage < -20 THEN \"< -20%\"\r\n    WHEN profit_percentage BETWEEN -20 AND -15 THEN \"-20% à -15%\"\r\n    WHEN profit_percentage BETWEEN -15 AND -10 THEN \"-15% à -10%\"\r\n    WHEN profit_percentage BETWEEN -10 AND -5 THEN \"-10% à -5%\"\r\n    WHEN profit_percentage BETWEEN -5 AND 0 THEN \"-5% à 0%\"\r\n    WHEN profit_percentage BETWEEN 0 AND 5 THEN \"0% à 5%\"\r\n    WHEN profit_percentage BETWEEN 5 AND 10 THEN \"5% à 10%\"\r\n    WHEN profit_percentage BETWEEN 10 AND 15 THEN \"10% à 15%\"\r\n    WHEN profit_percentage BETWEEN 15 AND 20 THEN \"15% à 20%\"\r\n    WHEN profit_percentage BETWEEN 20 AND 30 THEN \"20% à 30%\"\r\n    ELSE \"> 30%\"\r\n  END AS profit_range,\r\n  COUNT(*) AS trade_count,\r\n  CASE\r\n    WHEN profit_percentage < -20 THEN 1\r\n    WHEN profit_percentage BETWEEN -20 AND -15 THEN 2\r\n    WHEN profit_percentage BETWEEN -15 AND -10 THEN 3\r\n    WHEN profit_percentage BETWEEN -10 AND -5 THEN 4\r\n    WHEN profit_percentage BETWEEN -5 AND 0 THEN 5\r\n    WHEN profit_percentage BETWEEN 0 AND 5 THEN 6\r\n    WHEN profit_percentage BETWEEN 5 AND 10 THEN 7\r\n    WHEN profit_percentage BETWEEN 10 AND 15 THEN 8\r\n    WHEN profit_percentage BETWEEN 15 AND 20 THEN 9\r\n    WHEN profit_percentage BETWEEN 20 AND 30 THEN 10\r\n    ELSE 11\r\n  END AS range_order\r\nFROM (\r\n  SELECT\r\n    CASE\r\n      WHEN type = \"LONG\" THEN ((closePrice - entryPrice) / entryPrice) * 100 * ${leverage} - ((${leverage}+1)*0.15 + 0.1)\r\n      WHEN type = \"SHORT\" THEN ((entryPrice - closePrice) / entryPrice) * 100 * ${leverage} - ((${leverage}+1)*0.15 + 0.1)\r\n    END AS profit_percentage\r\n  FROM\r\n    BT_trades\r\n  WHERE\r\n    strategyId = '${strategy_id}'\r\n) AS profits\r\nGROUP BY profit_range, range_order\r\nORDER BY range_order;\r\n"
    }
   ]
  },
  {
   "title": "Cumulative per",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "dataset": "backtest",
     "rawSql": "SELECT\r\n    t.closeTs AS closeTimestamp,\r\n    @cumulative_profit := @cumulative_profit + \r\n    CASE \r\n        WHEN t.type = 'LONG' THEN ((t.closePrice - t.entryPrice) / t.entryPrice) * 100 * ${leverage} - ((${leverage}+1)*0.15 + 0.1)\r\n        WHEN t.type = 'SHORT' THEN ((t.entryPrice - t.closePrice) / t.entryPrice) * 100 * ${leverage} - ((${leverage}+1)*0.15 + 0.1)\r\n    END AS cumulative_portfolio_percentage\r\nFROM \r\n    BT_trades t, \r\n    (SELECT @cumulative_profit := 0) AS init\r\nWHERE \r\n    t.strategyId = '${strategy_id}'\r\n    AND t.closeTs IS NOT NULL\r\nORDER BY \r\n    t.closeTs ASC;\r\n"
    }
   ]
  },
  {
   "title": "Nombre de trades par mois",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "dataset": "backtest",
     "rawSql": "SELECT\r\n    DATE_FORMAT(t.closeTs, '%Y-%m') AS month,  -- Format de la date en année-mois\r\n    COUNT(*) AS trade_count,                  -- Nombre de trades par mois\r\n    ROUND(SUM(\r\n        CASE \r\n            WHEN t.type = 'LONG' THEN ((t.closePrice - t.entryPrice) / t.entryPrice) * ${leverage} * 100 - ((${leverage}*2*0.1) + 0.1)\r\n            WHEN t.type = 'SHORT' THEN ((t.entryPrice - t.closePrice) / t.entryPrice) * ${leverage} * 100 - ((${leverage}*2*0.1) + 0.1)\r\n        END\r\n    ), 2) AS Profit\r\nFROM \r\n    BT_trades t\r\nWHERE \r\n    t.strategyId = '${strategy_id}'          -- Filtrage par ID de stratégie\r\n    AND t.closeTs IS NOT NULL                -- Assurer que le trade est clôturé\r\nGROUP BY \r\n    DATE_FORMAT(t.closeTs, '%Y-%m')          -- Grouper par mois\r\nORDER BY \r\n    month ASC;                               -- Trier les résultats par mois\r\n\r\n"
    }
   ]
  }
 ]
}