{
 "title": "Trader Global",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "user", "label": "User", "query": "select username from T_users;" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT \r\n    t.symbol,\r\n    t.entryTs,\r\n    t.closeTs,\r\n    t.entryPrice,\r\n    t.closePrice,\r\n    t.quantity,\r\n    t.type,\r\n    ROUND(\r\n        CASE \r\n            WHEN t.type = 'LONG' THEN (t.closePrice * t.quantity) - (t.entryPrice * t.quantity)\r\n            WHEN t.type = 'SHORT' THEN (t.entryPrice * t.quantity) - (t.closePrice * t.quantity)\r\n        END, 2) AS profit_usd,\r\n    ROUND(TIMESTAMPDIFF(SECOND, t.entryTs, t.closeTs) / 3600, 2) AS duration_hours,\r\n    ROUND(\r\n        CASE \r\n            WHEN t.type = 'LONG' THEN ((t.closePrice - t.entryPrice) / t.entryPrice) * 100\r\n            WHEN t.type = 'SHORT' THEN ((t.entryPrice - t.closePrice) / t.entryPrice) * 100\r\n        END, 2) AS profit_percentage\r\nFROM \r\n    T_trades t\r\nJOIN \r\n    T_strategies s ON t.id_strategy = s.id\r\nJOIN \r\n    T_users u ON s.userId = u.id\r\nWHERE \r\n    u.username = '${user}';\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Taux des trades positifs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT \r\n    ROUND((SUM(\r\n        CASE \r\n            WHEN (t.type = 'LONG' AND t.closePrice > t.entryPrice) OR\r\n                 (t.type = 'SHORT' AND t.entryPrice > t.closePrice)\r\n            THEN 1 ELSE 0 END\r\n    ) / COUNT(*)) * 100, 2) AS positive_trade_percentage\r\nFROM \r\n    T_trades t\r\nJOIN \r\n    T_strategies s ON t.id_strategy = s.id\r\nJOIN \r\n    T_users u ON s.userId = u.id\r\nWHERE \r\n    t.closePrice IS NOT NULL \r\n    AND u.username = '${user}';\r\n"
    }
   ]
  },
  {
   "title": "Moyenne des profits des trades en pourcentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "\r\n\r\nSELECT \r\n    ROUND(AVG(\r\n        CASE \r\n            WHEN t.type = 'LONG' THEN ((t.closePrice - t.entryPrice) / t.entryPrice) * 100 * s.leverage\r\n            WHEN t.type = 'SHORT' THEN ((t.entryPrice - t.closePrice) / t.entryPrice) * 100 * s.leverage\r\n        END), 2) AS avg_profit_percentage\r\nFROM \r\n    T_trades t\r\nJOIN \r\n    T_strategies s ON t.id_strategy = s.id\r\nJOIN \r\n    T_users u ON s.userId = u.id\r\nWHERE \r\n    t.closePrice IS NOT NULL \r\n    AND u.username = '${user}';\r\n"
    }
   ]
  },
  {
   "title": "Total des bénéfices ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT \r\n    ROUND(SUM(\r\n        CASE \r\n            WHEN t.type = 'LONG' THEN (t.closePrice * t.quantity) - (t.entryPrice * t.quantity)\r\n            WHEN t.type = 'SHORT' THEN (t.entryPrice * t.quantity) - (t.closePrice * t.quantity)\r\n        END), 2) AS total_profit_usd\r\nFROM \r\n    T_trades t\r\nJOIN \r\n    T_strategies s ON t.id_strategy = s.id\r\nJOIN \r\n    T_users u ON s.userId = u.id\r\nWHERE \r\n    u.username = '${user}';\r\n"
    }
   ]
  },
  {
   "title": "Somme des profits des trades en pourcentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "\r\n\r\nSELECT \r\n    ROUND(SUM(\r\n        CASE \r\n            WHEN t.type = 'LONG' THEN ((t.closePrice - t.entryPrice) / t.entryPrice) * 100 * s.leverage\r\n            WHEN t.type = 'SHORT' THEN ((t.entryPrice - t.closePrice) / t.entryPrice) * 100 * s.leverage\r\n        END), 2) AS avg_profit_percentage\r\nFROM \r\n    T_trades t\r\nJOIN \r\n    T_strategies s ON t.id_strategy = s.id\r\nJOIN \r\n    T_users u ON s.userId = u.id\r\nWHERE \r\n    t.closePrice IS NOT NULL \r\n    AND u.username = '${user}';\r\n"
    }
   ]
  },
  {
   "title": "Nnombre de trades",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "trades" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "\r\n\r\nSELECT \r\n    COUNT(t.id) as tradeCount\r\nFROM \r\n    T_trades t\r\nJOIN \r\n    T_strategies s ON t.id_strategy = s.id\r\nJOIN \r\n    T_users u ON s.userId = u.id\r\nWHERE \r\n    t.closePrice IS NOT NULL \r\n    AND u.username = '${user}';\r\n"
    }
   ]
  },
  {
   "title": "Total des bénéfices de la stratégie",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT \r\n    closeTimestamp,\r\n    @cumulative_profit := @cumulative_profit + profit_usd AS cumulative_profit_usd\r\nFROM (\r\n    SELECT \r\n        t.closeTs AS closeTimestamp,\r\n        ROUND(\r\n            CASE \r\n                WHEN t.type = 'LONG' THEN (t.closePrice * t.quantity) - (t.entryPrice * t.quantity)\r\n                WHEN t.type = 'SHORT' THEN (t.entryPrice * t.quantity) - (t.closePrice * t.quantity)\r\n            END, 2) AS profit_usd\r\n    FROM \r\n        T_trades t\r\n    JOIN \r\n        T_strategies s ON t.id_strategy = s.id\r\n    JOIN \r\n        T_users u ON s.userId = u.id\r\n    WHERE \r\n        u.username = '${user}'\r\n        AND t.closeTs IS NOT NULL -- Considérer uniquement les trades clôturés\r\n    ORDER BY \r\n        t.closeTs ASC\r\n) AS profits, (SELECT @cumulative_profit := 0) AS init;\r\n"
    }
   ]
  }
 ]
}